language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "rovingeye-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
  provider: releases
  user: ${env.GITHUB_USER}
  password: ${env.GITHUB_PASS}
  file:
    - imageserver-*
  skip_cleanup: true
  on:
    repo: rovingeye/imageserver
    tags: true