language: java
jdk:
  - oraclejdk8

env:
  global:
    - CC_TEST_REPORTER_ID=3a88c6e42da81a5b42b820888f65bb16ff669f0b92872a53ba040269031f1fc6

script:
  - './mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install \
       sonar:sonar \
       -Dsonar.organization=rovingeye-github \
       -Dsonar.host.url=https://sonarcloud.io \
       -Dsonar.login=9f3caa32fc4211f87f1931fa0167eb50e14dc0fc'