spring:
  cache:
    cache-names: images
    caffeine:
      spec: maximumSize=1000, expireAfterAccess=1d, initialCapacity=500
  application:
    name: Imageserver

imageserver:
  directory: /tmp/imageserver
  default: default.jpg

